### ISSUE TITLE
J. Resume Projects Addendum

### ISSUE THREAD

**Issue by JoshusTenakhongva** [JoshusTenakhongva/Example_Repo#6]
- [x] Add Link to GoogleDoc Resume
    - [Google doc link](https://docs.google.com/document/d/1wnpJ0m9vcbbWB55LEiAJifBRJ0EZL9TKUGjv4W3B7e0/edit?usp=sharing)
 
- [x] Add projects to resume and more closely mimic other resume styles

- [x] Resume Reformat [Link](https://docs.google.com/document/d/1sMaE_pTx_-6JpZjithYu3-hZMyK1UyK6b1l2d4-0Atc/edit?usp=sharing)
    - [x] [Use a better template](https://app.sharpestminds.com/static-page/your-resume)
    - [x] Version w and w/o Red Lobster
    - [x] Break down to single page
    - [x] Projects/education/awards/internship look good

**Comment by CLuiz** [comment]
Nice work! I think we should fit some info regarding your projects on there, but we can talk about it next week.
